### ISSUE TITLE
AppSignal is halting the CI due to the timeout Error.

### ISSUE THREAD

**Issue by collegeimprovements** [appsignal/appsignal-javascript#580]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

**Bug Description**
We are getting the `timeout` error 8 out of 10 times in our CI. 
This keep happening with different `timeout` values consistently.

Here is the error trace:

```
[webpack-cli] Error: AppSignal Plugin: Error: timeout of 180000ms exceeded
    at AppsignalPlugin.<anonymous> (/project_path/node_modules/@appsignal/webpack/dist/cjs/index.js:73:31)
    at step (/project_path/node_modules/@appsignal/webpack/dist/cjs/index.js:33:23)
    at Object.throw (/project_path/node_modules/@appsignal/webpack/dist/cjs/index.js:14:53)
    at rejected (/project_path/node_modules/@appsignal/webpack/dist/cjs/index.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Additional context**
This is happening in our `CI` environment(circle-ci).

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700155394 (private link)
